// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb_Vf11CaKsfScA7c5bVlxidvNCtoF7Ek',
    appId: '1:791934457950:web:26c7eac87549c7484f7ccf',
    messagingSenderId: '791934457950',
    projectId: 'khata-kapi-cbc6f',
    authDomain: 'khata-kapi-cbc6f.firebaseapp.com',
    storageBucket: 'khata-kapi-cbc6f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiXs8e8oEmZpN0LWbCBCzHb3tONV41s-g',
    appId: '1:791934457950:android:d89512b5019d5f824f7ccf',
    messagingSenderId: '791934457950',
    projectId: 'khata-kapi-cbc6f',
    storageBucket: 'khata-kapi-cbc6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTrxACxHe6AYQ8aet_0ZjFPpVjZmxIgg8',
    appId: '1:791934457950:ios:d0f72b0d2bc4b4a94f7ccf',
    messagingSenderId: '791934457950',
    projectId: 'khata-kapi-cbc6f',
    storageBucket: 'khata-kapi-cbc6f.appspot.com',
    iosClientId: '791934457950-j1siug1nmk2l2fstn9mu79igvq8q9pfm.apps.googleusercontent.com',
    iosBundleId: 'com.example.khatakapi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTrxACxHe6AYQ8aet_0ZjFPpVjZmxIgg8',
    appId: '1:791934457950:ios:d0f72b0d2bc4b4a94f7ccf',
    messagingSenderId: '791934457950',
    projectId: 'khata-kapi-cbc6f',
    storageBucket: 'khata-kapi-cbc6f.appspot.com',
    iosClientId: '791934457950-j1siug1nmk2l2fstn9mu79igvq8q9pfm.apps.googleusercontent.com',
    iosBundleId: 'com.example.khatakapi',
  );
}
